# Site settings
title: Damien's blog
#email: damien.gonot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Damien
summary: >
  Welcome! My name is Damien, I'm 23 years old and I currently live in Montréal, Québec
  (at the time of writing).
  I also currently work at Busbud as a Customer Acquisition Associate.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mewfree.github.io" # the base hostname & protocol for your site
#twitter_username: mewfree
github_username: mewfree

# Build settings
markdown: kramdown
