# Site settings
title: Damien's blog
#email: damien.gonot@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Damien, a 22 years old webmarketer currently working at Busbud.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mewfree.github.io" # the base hostname & protocol for your site
#twitter_username: mewfree
github_username: mewfree

# Build settings
markdown: kramdown
